### ISSUE TITLE
获取圣思园张龙JVM笔记

### ISSUE THREAD

**Issue by justzzk** [GJXAIOU/Notes#1]
您好，在B站看到您上传的圣思园张龙JVM视频看到这个项目的，本来想直接下载下来但不知什么原因网速一直只有几k，而且还不能下载部分文件，希望能麻烦您发送该课程笔记到邮箱2514379314@qq.com,十分感谢！

**Comment by GJXAIOU** [comment]
已发送到邮箱，因为笔记会不断的修正更改，所以建议使用 GitHub 保持能看到最新版本，Chrome 可以使用 Enhanced GitHub 插件来实现单个文件下载。
