### ISSUE TITLE
JVM笔记

### ISSUE THREAD

**Issue by Hmsh** [GJXAIOU/Notes#2]
您好，看了您在b占发的笔记连接，想要参考您记得JVM笔记学习，邮箱2575032083@qq.com 麻烦您发我一份，谢谢。

**Comment by GJXAIOU** [comment]
我有点没太明白，链接打开不就是笔记吗，是在下载使用过程中出现问题了吗

**Comment by GJXAIOU** [comment]
已发送到邮箱，因为笔记会不断的修正更改，所以建议使用 GitHub 保持能看到最新版本，Chrome 可以使用 Enhanced GitHub 插件来实现单个文件下载。
同时笔记中有错误的十分感谢能否指正。
